maj

diff --git a/TP3/cordic/Makefile b/TP3/cordic/Makefile
--- a/TP3/cordic/Makefile
+++ b/TP3/cordic/Makefile
@@ -3,6 +3,9 @@ LDFLAGS=-lm
 MODEL=cordic
 ADDRWD  = 8#		bit width of addresses for the rom
 VALWD   = 8#		bit width of operands for the rom
+CYCLES  = 4000 #	number of cycles to simulate (should be suffisant for all triplets)
+VALNB   = $(shell awk -v ADDRWD=$(ADDRWD) 'BEGIN{print int((2**ADDRWD)/3) }')
+LASTPT  = $(shell awk -v VALNB=$(VALNB) 'BEGIN{print 3*VALNB-1}')
 
 help:
 	@echo ""
@@ -29,12 +32,11 @@ cercle:
 
 valid_cor: 
 	vasy -a -I vhd -p -o $(MODEL)_cor $(MODEL)_cor 
-	export PATNAME=$(MODEL)_cor DECSIG;
-	genpat $(MODEL)_pat
+	export PATNAME=$(MODEL)_cor DECSIG; genpat $(MODEL)_pat
 	asimut -b $(MODEL)_cor $(MODEL)_cor $(MODEL)_cor_res
 
 valid_net:
-	$(CC) $(CFLAGS) rom.c -o rom
+	$(CC) $(CFLAGS) rom.c -lm -o rom
 	./rom	$(ADDRWD) $(VALWD) > rom.txt
 	export PATNAME=$(MODEL)_net; genpat $(MODEL)_pat
 	 
@@ -48,10 +50,21 @@ valid_net:
 potatoe:
 	$(CC) $(CFLAGS) rom.c -lm -o rom
 	./rom	$(ADDRWD) $(VALWD) > rom.txt
-# 	export PATNAME=$(MODEL)_tb ADDRWD=$(ADDRWD) VALWD=$(VALWD) CYCLES=$(CYCLES);
-# 	genpat $(MODEL)_pat
+	export PATNAME=$(MODEL)_tb ADDRWD=$(ADDRWD) VALWD=$(VALWD) CYCLES=$(CYCLES); genpat $(MODEL)_pat2
 	gcc -w -E -DADDRWD=$(ADDRWD) -DVALWD=$(VALWD) -DLASTPT=$(LASTPT) $(MODEL)_data.vhd.c | grep -v "^#" > $(MODEL)_data.vhd
+	
+	vasy -a -I vhd -p -o $(MODEL)_ctl $(MODEL)_ctl
+	vasy -a -I vhd -p -o $(MODEL)_dp $(MODEL)_dp
+	vasy -a -I vhd -p -o $(MODEL)_net $(MODEL)_net
+	vasy -a -I vhd -p -o $(MODEL)_data $(MODEL)_data 
+	vasy -a -I vhd -p -o $(MODEL)_tb   $(MODEL)_tb 
+	vasy -a -I vhd -p -o one_in_three_out one_in_three_out
+	vasy -a -I vhd -p -o two_in_one_out two_in_one_out
+# 	asimut $(MODEL)_tb $(MODEL)_tb $(MODEL)_tbres
+	asimut $(MODEL)_tb $(MODEL)_tb $(MODEL)_tbres | awk '/pattern/{printf("->"$$3" "$$4"\r")}END{print}'
+	@grep ": ?1" $(MODEL)_tbres.pat || echo "Lucky no error"
 
+	
 synthesis:
 	boom $(MODEL)_ctl $(MODEL)_ctl_boom
 	boog $(MODEL)_ctl_boom $(MODEL)_ctl_boog
@@ -77,8 +90,10 @@ clean:
 		$(MODEL)_cor.pat $(MODEL)_cor_res.pat \
 		$(MODEL)_dp.vbe $(MODEL)_ctl.vbe $(MODEL)_net.vst \
 		$(MODEL)_net.pat $(MODEL)_net_res.pat \
+		${MODEL}_tb_model.vbe\
 		*.xsc \
 		*.vst \
 		*.pat \
 		.txt \
+		*.vbe
 		a.out
